# Generated by Django 3.0.4 on 2020-03-19 04:35

from django.db import migrations, models
import django_extensions.db.fields
import urls.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True
                    ),
                ),
                (
                    "modified_at",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=400, null=True)),
                ("original_url", models.URLField(max_length=400)),
                (
                    "url_identifier",
                    models.CharField(
                        default=urls.models.url_identifier_generator, max_length=200
                    ),
                ),
                ("access_count", models.IntegerField(default=0)),
            ],
        )
    ]
